version: "3.4"
services:
  api:
    image: ghcr.io/andrewsutliff-insight/fabrikam-api:latest
    ports:
      - "3001:3001"

  webapp:
    image: ghcr.io/andrewsutliff-insight/fabrikam-webapp:latest
    depends_on:
        - api
    environment:
        CONTENT_API_URL: http://api:3001
    ports:
        - "3000:80"   