version: "3.4"
services:
  api:
    image: ghcr.io/grhoads-insight/fabrikam-api:latest
    ports:
      - "3001:3001"

  web:
    image: local-fabrikam-web:latest #ghcr.io/grhoads-insight/fabrikam-web:latest are in instructinos but get "ERROR:UNKNOWN MANIFEST" when use docker-compose up
    depends_on:
        - api
    environment:
      CONTENT_API_URL: http://api:3001
    ports:
        - "3000:80"